// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cshtjqkcjohrzkkkfdjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzaHRqcWtjam9ocnpra2tmZGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Mjc4MzcsImV4cCI6MjA3MzIwMzgzN30.P2Pb4MhoBeU6HBgljLvkCW9h4HBWjl5JnImjp2tswuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});